SELECT * FROM products
WHERE title LIKE $1
OR title LIKE $2
OR title LIKE $3
OR title LIKE $4
OR category LIKE $1
OR category LIKE $2
OR category LIKE $3
OR category LIKE $4
OR description LIKE $1
OR description LIKE $2
OR description LIKE $3
OR description LIKE $4;